//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.RequestLogs = new HashSet<RequestLog>();
        }
    
        public int ID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int Client { get; set; }
        public int Equipment { get; set; }
        public int FaultType { get; set; }
        public int Priority { get; set; }
        public int Status { get; set; }
        public int Employee { get; set; }
    
        public virtual Client Client1 { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Equipment Equipment1 { get; set; }
        public virtual FaultType FaultType1 { get; set; }
        public virtual Priority Priority1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestLog> RequestLogs { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
