//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestLog
    {
        public int ID { get; set; }
        public System.DateTime LogDate { get; set; }
        public string Description { get; set; }
        public int RequestID { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
